targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          include:
            - "lib/data/models/**.dart"
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false

global_options:
  json_serializable:
    options:
      explicit_to_json: true
      field_rename: none
      create_factory: true
      create_to_json: true
